### ISSUE TITLE
Protección de Spawn debería removerse al disparar

### ISSUE THREAD

**Issue by Maxi605** [OsweRRR/jCTF-by-Digi#3]
Por lo que vi la protección de spawn solo se remueve si le das un golpe a otro jugador (si se remueve al disparar solamente entonces tarda demasiado en hacerlo) lo cual otorga una gigantezca ventaja al que acaba de spawnear, estaría bueno que al disparar (sin darle al jugador) se le remueva instantaneamente la protección.

**Comment by OsweRRR** [comment]
Hola, se dejo la funcion default que trae la version original ya que se removio por error la funcion!.
