### ISSUE TITLE
problema de respawn

### ISSUE THREAD

**Issue by stefanofabi** [OsweRRR/jCTF-by-Digi#4]
Acabo de instalar el modo y solo se puede jugar 1 vs 1, el resto de los jugadores aparecen muertos y no pueden respawnear.

utilice las ultimas versiones de regamedll, reapi, rehlds y amxmodx 1.9

alguien mas le pasa lo mismo?

**Comment by OsweRRR** [comment]
Hola amigo disculpa el tiempo, he hecho algunas actualizaciones incluyendo el game.cfg del regamedll. Prueba y dime que tal, hice unos cambios al sistema de respawn!.
